# -*- coding: utf-8 -*-
"""HTML Quick Styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iizxfqEHkUz5VVHxpnLW5FHC-0Nu8qtC
"""

!pip install -U transformers

from transformers import pipeline

pipe = pipeline("text-generation",model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role":"user","content":"who are you?"},
]
pipe(messages)

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)

print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

import gradio as gr
import random
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List

# ----------------------------
# Color palettes
# ----------------------------

palettes: Dict[str, List[str]] = {
    "modern": ["#2563eb", "#1e40af", "#f1f5f9", "#0f172a"],
    "vibrant": ["#ef4444", "#f97316", "#fde68a", "#1f2937"],
    "ocean": ["#0284c7", "#0ea5e9", "#e0f2fe", "#082f49"],
    "forest": ["#166534", "#22c55e", "#dcfce7", "#052e16"],
    "sunset": ["#f97316", "#fb923c", "#ffedd5", "#7c2d12"],
    "luxury": ["#111827", "#374151", "#f9fafb", "#000000"],
    "creative": ["#7c3aed", "#a855f7", "#ede9fe", "#2e1065"],
    "minimal": ["#6b7280", "#9ca3af", "#f3f4f6", "#111827"]
}

# ----------------------------
# HTML Generator
# ----------------------------

def generate_html(title: str, description: str, style: str) -> Tuple[str, str]:

    colors = palettes.get(style, palettes["modern"])

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html = f"""
<!DOCTYPE html>
<html>
<head>
<title>{title}</title>

<style>
body {{
font-family: Arial;
background:{colors[2]};
color:{colors[3]};
margin:0;
}}

header {{
background:{colors[0]};
color:white;
padding:40px;
text-align:center;
}}

section {{
padding:40px;
}}

button {{
background:{colors[1]};
color:white;
border:none;
padding:12px 20px;
border-radius:6px;
}}

footer {{
background:{colors[3]};
color:white;
text-align:center;
padding:20px;
}}
</style>

</head>

<body>

<header>
<h1>{title}</h1>
<p>{description}</p>
<button>Get Started</button>
</header>

<section>
<h2>About</h2>
<p>This section describes your website.</p>
</section>

<section>
<h2>Portfolio</h2>
<p>Show your work here.</p>
</section>

<section>
<h2>Contact</h2>
<p>Email: example@email.com</p>
</section>

<footer>
<p>© 2026 {title}</p>
<p>Generated at {timestamp}</p>
</footer>

</body>
</html>
"""

    # Clean extra spaces using regex
    html_clean = re.sub(r"\n\s+\n", "\n", html)

    return html_clean, html_clean


# ----------------------------
# Palette Viewer
# ----------------------------

def show_palette(style: str) -> str:
    return " | ".join(palettes.get(style))


# ----------------------------
# Templates
# ----------------------------

templates: Dict[str, str] = {
"Portfolio":"Hero + About + Portfolio + Contact",
"Business":"Hero + Services + Testimonials + Contact",
"Landing Page":"Hero + Features + Pricing + CTA",
"Blog":"Header + Articles + Sidebar + Footer"
}

def show_template(name: str) -> str:
    return templates.get(name)


# ----------------------------
# Export Project (JSON example)
# ----------------------------

def export_project(title: str, description: str, style: str) -> str:

    data = {
        "title": title,
        "description": description,
        "style": style,
        "created": datetime.now().isoformat()
    }

    return json.dumps(data, indent=2)


# ----------------------------
# Gradio UI
# ----------------------------

with gr.Blocks(title="HTML Quick-Styler Advanced") as demo:

    gr.Markdown("# 🎨 HTML Quick-Styler Advanced")
    gr.Markdown("Professional HTML Page Generator with Auto-Styling")

    with gr.Tabs():

        # Generate Page
        with gr.Tab("⚡ Generate Page"):

            with gr.Row():

                with gr.Column():

                    title = gr.Textbox(
                        label="Page Title",
                        value="Modern Portfolio Website"
                    )

                    description = gr.Textbox(
                        label="Page Description & Sections",
                        lines=4,
                        value="Hero section with welcome message, portfolio gallery, testimonials, contact form and footer"
                    )

                    style = gr.Dropdown(
                        choices=list(palettes.keys()),
                        value="modern",
                        label="Color Style"
                    )

                    generate_btn = gr.Button("⚡ Generate HTML")

                with gr.Column():

                    output = gr.Code(
                        label="Generated HTML/CSS",
                        language="html"
                    )

        # Live Preview
        with gr.Tab("👁 Live Preview"):
            preview = gr.HTML()

        # Color Palettes
        with gr.Tab("🎨 Color Palettes"):

            palette_style = gr.Dropdown(
                choices=list(palettes.keys()),
                value="modern",
                label="Select Style"
            )

            palette_btn = gr.Button("Show Palette")

            palette_output = gr.Textbox(label="Palette Colors")

        # Templates
        with gr.Tab("📄 Templates"):

            template_name = gr.Dropdown(
                choices=list(templates.keys()),
                label="Select Template"
            )

            template_btn = gr.Button("Show Template")

            template_output = gr.Textbox(label="Template Structure")

        # Guide
        with gr.Tab("📘 Guide"):

            gr.Markdown("""

### How to Use HTML Quick-Styler

1️⃣ Enter **Page Title**

2️⃣ Enter **Page Description**

3️⃣ Choose **Color Style**

4️⃣ Click **Generate HTML**

5️⃣ View **Live Preview**

6️⃣ Copy the generated HTML for your website

### Features
- Automatic CSS styling
- Professional color palettes
- Ready-to-use website templates
""")

    # Button actions

    generate_btn.click(
        generate_html,
        inputs=[title, description, style],
        outputs=[output, preview]
    )

    palette_btn.click(
        show_palette,
        inputs=palette_style,
        outputs=palette_output
    )

    template_btn.click(
        show_template,
        inputs=template_name,
        outputs=template_output
    )

demo.launch(share=True)